[project]
name = "reflection_tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "pandas",
    "seaborn",
    "plotly",
    "openpyxl",
    "anthropic>=1.3.0",
    "pydantic>=2.13.5",
    "supabase>=2.31.0",
]

[dependency-groups]
dev = [
    "ipykernel",
    "itables",
    "nbformat",
]
